## Часть 1: Введение в Pandas

Pandas - это библиотека Python для работы с данными. Она предоставляет мощные инструменты для анализа и манипуляции данными.

### Установка Pandas

Для начала убедитесь, что у вас установлена библиотека Pandas. Если ее нет, установите ее с помощью команды:

In [40]:
!pip install pandas

Requirement already satisfied: pandas in /Users/porcupine15/projects/.venv/lib/python3.14/site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in /Users/porcupine15/projects/.venv/lib/python3.14/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/porcupine15/projects/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/porcupine15/projects/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

## Импорт библиотеки
Давайте начнем с импорта библиотеки Pandas:

In [41]:
import pandas as pd

## Часть 2: Работа с данными
### Чтение данных
Мы будем использовать датасет Titanic. Давайте прочитаем данные из CSV файла.

In [42]:
# Чтение данных из файла 'titanic.csv'
df = pd.read_csv('titanic.csv')

### Предпросмотр данных
Для первого ознакомления с данными давайте выведем первые несколько строк.

In [43]:
# Вывод первых 5 строк данных
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Информация о данных
Чтобы получить общую информацию о данных, воспользуйтесь методом .info().

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

### Работа с NaN
Часто данные содержат пропущенные значения, которые представляются как NaN (Not a Number). Pandas предоставляет удобные методы для работы с ними.

Проверка на наличие NaN. Методы fillna и dropna возвращают новые Dataframe, проверьте нет ли в них NaN

In [45]:
# Проверка на наличие NaN в DataFrame
df.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

Заполнение NaN

In [46]:
# Заполнение NaN определенным значением (например, нулем)
df = df.fillna(0)

Удаление строк с NaN

In [47]:
# Удаление строк, содержащих NaN
df = df.dropna()

## Часть 3: Обработка DataFrame
### Выбор данных
Pandas позволяет выбирать данные по индексам, меткам столбцов и условиям.

In [48]:
# Выбор столбца по метке
# Используйте синтаксис DataFrame['название_столбца']
df['Age']

# Выбор нескольких столбцов
# Используйте синтаксис DataFrame[['столбец_1', 'столбец_2']]
df[['Age', 'PassengerId']]

# Выбор строк по индексу
# Используйте метод .loc[]
df.loc[5]

# Выбор строк и столбцов по условию
# Используя логические операции, выберите мужчин старше 30
condition = (df['Sex'] == 'male') & (df['Age'] > 30)
over30 = df[condition]
res = df.loc[condition, ['PassengerId', 'Name', 'Age']]
print(res)

     PassengerId                                  Name   Age
4              5              Allen, Mr. William Henry  35.0
6              7               McCarthy, Mr. Timothy J  54.0
13            14           Andersson, Mr. Anders Johan  39.0
20            21                  Fynney, Mr. Joseph J  35.0
21            22                 Beesley, Mr. Lawrence  34.0
..           ...                                   ...   ...
867          868  Roebling, Mr. Washington Augustus II  31.0
872          873              Carlsson, Mr. Frans Olof  33.0
873          874           Vander Cruyssen, Mr. Victor  47.0
881          882                    Markun, Mr. Johann  33.0
890          891                   Dooley, Mr. Patrick  32.0

[202 rows x 3 columns]

### Сортировка данных
Сортировка данных по значениям столбцов.

In [49]:
# Сортировка данных по столбцу 'столбец_1' по возрастанию
# Используйте метод .sort_values()
# write your code here
print(df.sort_values(by='Age'))

     PassengerId  Survived  Pclass                                    Name  \
667          668         0       3              Rommetvedt, Mr. Knud Paust
128          129         1       3                       Peter, Miss. Anna
533          534         1       3  Peter, Mrs. Catherine (Catherine Rizk)
284          285         0       1              Smith, Mr. Richard William
538          539         0       3                Risien, Mr. Samuel Beard
..           ...       ...     ...                                     ...
116          117         0       3                    Connors, Mr. Patrick
493          494         0       1                 Artagaveytia, Mr. Ramon
96            97         0       1               Goldschmidt, Mr. George B
851          852         0       3                     Svensson, Mr. Johan
630          631         1       1    Barkworth, Mr. Algernon Henry Wilson

        Sex   Age  SibSp  Parch    Ticket     Fare  Cabin Embarked
667    male   0.0      0      0    312993   7.7750      0        S
128  female   0.0      1      1      2668  22.3583  F E69        C
533  female   0.0      0      2      2668  22.3583      0        C
284    male   0.0      0      0    113056  26.0000    A19        S
538    male   0.0      0      0    364498  14.5000      0        S
..      ...   ...    ...    ...       ...      ...    ...      ...
116    male  70.5      0      0    370369   7.7500      0        Q
493    male  71.0      0      0  PC 17609  49.5042      0        C
96     male  71.0      0      0  PC 17754  34.6542     A5        C
851    male  74.0      0      0    347060   7.7750      0        S
630    male  80.0      0      0     27042  30.0000    A23        S

[891 rows x 12 columns]

### Группировка данных
Pandas также позволяет группировать данные и выполнять агрегирующие операции.

In [50]:
# Найдите долю выживших среди всех PClass
print(df.groupby('Pclass')['Survived'].mean())

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

## Часть 4: Задания для практики
Прочитайте данные из файла 'titanic.csv'.
Проверьте, есть ли пропущенные значения в данных и заполните их нулями.
Выведите первые 10 строк данных.
Выберите только те строки, где значение в столбце 'Age' больше 30.
Отсортируйте данные по столбцу 'Fare' в порядке убывания.
Сгруппируйте данные по столбцу 'Pclass' и вычислите средний возраст ('Age') для каждого класса.

In [51]:
data = pd.read_csv('titanic.csv')

In [52]:
data.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [53]:
data = data.fillna(0)

In [54]:
print('Первые 10 строк данных:')
data.head(10)

Первые 10 строк данных:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,0,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,0,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,0,S
5,6,0,3,"Moran, Mr. James",male,0.0,0,0,330877,8.4583,0,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,0,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,0,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,0,C

In [55]:
data_age_30 = data[data['Age'] > 30]
print(f"\nКоличество строк с Age > 30: {len(data_age_30)}")
print("Первые 5 строк отфильтрованных данных:")
print(data_age_30.head(5))

Количество строк с Age > 30: 305
Первые 5 строк отфильтрованных данных:
    PassengerId  Survived  Pclass  \
1             2         1       1
3             4         1       1
4             5         0       3
6             7         0       1
11           12         1       1

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                            Allen, Mr. William Henry    male  35.0      0
6                             McCarthy, Mr. Timothy J    male  54.0      0
11                           Bonnell, Miss. Elizabeth  female  58.0      0

    Parch    Ticket     Fare Cabin Embarked
1       0  PC 17599  71.2833   C85        C
3       0    113803  53.1000  C123        S
4       0    373450   8.0500     0        S
6       0     17463  51.8625   E46        S
11      0    113783  26.5500  C103        S

In [56]:
data_sorted_by_fare = data.sort_values(by='Fare', ascending=False)
print("\nПервые 5 строк после сортировки по Fare (от большей к меньшей):")
print(data_sorted_by_fare[['PassengerId', 'Fare', 'Age', 'Pclass']].head(5))

Первые 5 строк после сортировки по Fare (от большей к меньшей):
     PassengerId      Fare   Age  Pclass
258          259  512.3292  35.0       1
737          738  512.3292  35.0       1
679          680  512.3292  36.0       1
88            89  263.0000  23.0       1
27            28  263.0000  19.0       1

In [57]:
mean_age_by_class = data.groupby('Pclass')['Age'].mean()
print("\nСредний возраст по классам (Pclass):")
print(mean_age_by_class)

Средний возраст по классам (Pclass):
Pclass
1    32.923241
2    28.091467
3    18.177026
Name: Age, dtype: float64